import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import  Input  from '../components/input'
import Boton from '../components/boton'
import Video from '../components/video'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <span><Input type="text"/>
        <Boton caption="Enviar"/>
        </span>
        <Video src="https://www.w3schools.com/tags/movie.ogg" width="320" height="480" type="video/ogg"></Video>
      </main>
    </>
  )
}
